### ISSUE TITLE
Ability to use a compressed pre-populated sqlite db in assets

### ISSUE THREAD

**Issue by deanezra** [pardom-zz/ActiveAndroid#224]
I am currently using your library with a sqlite db pre-populated in the apps assets dir.
However the file is quite large uncompressed.

Please could you add support for storing the db file as a zip (the library could unzip it when copying it to /data/ dir).

The sqliteAssetHelper library for android does this nicely here on github (documented half way down readme):
https://github.com/jgilfelt/android-sqlite-asset-helper

Thanks

Dean

**Comment by vonloxley** [comment]
Since the database will be in a compressed .jar anyway, I don’t expect much impact. Could you tell us the different sizes of the final jars with and without the compressed database?

**Comment by deanezra** [comment]
Interesting, I have just run two builds (only difference is that I zipped the sqlite file in assets on second build, there is a small difference:
1. uncompressed sqlite db in assets of 36.4mb, end apk is =11.6 mb
2. compressed sqlite db in assets of 6.68mb, apk is = 9.9mb

Not as much difference as I expected, but I guess there is also another factor to take into account: startup time used to uncompress sqlite file at runtime.

Does this all go on in the main thread of app?

If so, I'm already seeing a sizeable delay in startup after adding the pre-populated db to assets (3-4 seconds on S3 handset).

PS: Brilliant library, saves lots of dev time.

**Comment by vonloxley** [comment]
Hi Dean!

Since the size-wise difference is not that large I’d vote against this change. 

Considering the delay during the startup: This should only happen during the first start, when the DB is copied. You could try setting the copy-buffer in DatabaseHelper.java line 108 to a more suitable value (4k or even 128k) and give it a try.

And yes, everything is done on the main-thread. But it’s shouldn’t  be a problem to move the openDatabase() in Cache.initialize() to a seperate thread.

Have Fun!

**Comment by deanezra** [comment]
I agree, the difference in size isn't worth the extra start-up time. 

Regarding init time: I hid the initialise time using a splash screen that closes after the ActiveAndroid.initialise() completed. so no need to move code into separate thread.

Thanks for your help and very quick responses

**Comment by SleeplessByte** [comment]
@deanezra You can now close this issue :)

**Comment by deanezra** [comment]
Closing issue
