### ISSUE TITLE
Autocompletion on one field

### ISSUE THREAD

**Issue by luxsyp** [pardom-zz/ActiveAndroid#350]
Hello I would like to be able to create an auto-completion based on my database,

my model look like this :

```
  @Table(name = "Drug")
  public class Item extends Model {

  @Column(name = "Name")
  public String name;

  @Column(name = "Desc")
  public String desc;

  @Column(name= "Type")
  public Integer type;
 }
```

I would like to be able to auto-complete on the name only without getting ALL my objects before.

Is there a way to only get a List<String>, where the String is the field name of my object without getting all the object (name+desc+type) ?

**Comment by jlhonora** [comment]
I believe you can't get a list of strings directly. Here's a (very insecure) alternative:

```
List<Item> items = new Select("Name").from(Item.class)
    .where("Name LIKE %" + input + "%").execute();

List<String> strings = new ArrayList<String>();

for (Item item : items) {
    strings.add(item.name);
}
```

It is insecure because SQL injection could occur. I don't know if ActiveAndroid has any anti-SQL injection utilities.

**Edit**: It doesn't have a built-in anti SQL injection mechanism, here's the part where arguments are added:

```
void addArguments(Object[] args) {
    for(Object arg : args) {
        if (arg.getClass() == boolean.class || arg.getClass() == Boolean.class) {
            arg = (arg.equals(true) ? 1 : 0);
        }
        mArguments.add(arg);
    }
}
```

**Edit 2**: Multiple statements are not supported in Android's `SQLiteDatabase` ([reference](http://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#execSQL%28java.lang.String,%20java.lang.Object[]%29)), so injection shouldn't be a problem.

**Comment by luxsyp** [comment]
sounds like I can start from this thx
