### ISSUE TITLE
Failed to invoke “model” with no args

### ISSUE THREAD

**Issue by fakemelvynkim** [pardom-zz/ActiveAndroid#372]
Why does the constructors don't get called?

**Comment by jlhonora** [comment]
From reading your logs, `Result()` was called, it just failed with a NPE. It can't find the TableInfo for the Results class : https://github.com/pardom/ActiveAndroid/blob/master/src/com/activeandroid/Model.java#L53

```
public Model() {
    mTableInfo = Cache.getTableInfo(getClass());
    // Here's where it fails
    idName = mTableInfo.getIdName();
}
```

Are you sure you're initializing the app correctly? Can you create a `Result` instance with pure ActiveAndroid, no Retrofit added? Something like this should do:

```
Result res = new Result();
res.save();
```

I'm not sure, but since the `Result` class has no columns, maybe there's no point in creating a table for it.

**Comment by fakemelvynkim** [comment]
@jihonora Thanks!! Your answer provided enough clue to solve the problem. Result() was not called through the `Callback` I received from `Retrofit` service.
